import Vue from 'vue';
import './styles';
import { GwtkIcon } from '@/components/System/Vuetify/GwtkIcon';
import { GwtkIconButton } from '@/components/System/Vuetify/GwtkIconButton';
import { GwtkMenu } from '@/components/System/Vuetify/GwtkMenu';
import { GwtkNavButton } from '@/components/System/Vuetify/GwtkNavButton';
import { GwtkChip } from '@/components/System/Vuetify/GwtkChip/';
import { GwtkPage } from '@/components/System/Vuetify/GwtkPage';
import { GwtkToolButton } from '@/components/System/Vuetify/GwtkToolButton';
import { GwtkTab } from '@/components/System/Vuetify/GwtkTab';
import { GwtkTabs } from '@/components/System/Vuetify/GwtkTabs';
import { GwtkTooltip } from '@/components/System/Vuetify/GwtkTooltip';
import { GwtkButton } from '@/components/System/Vuetify/GwtkButton';
import { GwtkCheckbox } from '@/components/System/Vuetify/GwtkCheckbox';
import { GwtkBadge } from '@/components/System/Vuetify/GwtkBadge';
import { GwtkListItem } from '@/components/System/Vuetify/GwtkListItem';
import { GwtkSwipePanel } from '@/components/System/Vuetify/GwtkSwipePanel';
import { GwtkTaskCard } from '@/components/System/Vuetify/GwtkTaskCard';
import { GwtkOverlay } from '@/components/System/Vuetify/GwtkOverlay';
import { GwtkSnackBar } from '@/components/System/Vuetify/GwtkSnackBar';
import { GwtkDegreesMinutesSeconds } from '@/components/System/Vuetify/GwtkDegreesMinutesSeconds';
import { GwtkExpansionPanel } from '@/components/System/Vuetify/GwtkExpansionPanel';
import { RgisPage } from '@/components/System/Vuetify/RgisPage';
import { GwtkSelectable } from '@/components/System/Vuetify/GwtkSelectable';
import { GwtkDraggableResizable } from '@/components/System/Vuetify/GwtkDraggableResizable';
import { GwtkDateTimePicker } from '@/components/System/Vuetify/GwtkDateTimePicker';
import { GwtkComponentHistory } from '@/components/System/Vuetify/GwtkComponentHistory';
import {GwtkDragAndDropArea} from '@/components/System/Vuetify/GwtkDragAndDropArea';


Vue.component( 'GwtkBadge', GwtkBadge );
Vue.component( 'GwtkButton', GwtkButton );
Vue.component( 'GwtkCheckbox', GwtkCheckbox );
Vue.component( 'GwtkChip', GwtkChip );
Vue.component( 'GwtkDegreesMinutesSeconds', GwtkDegreesMinutesSeconds );
Vue.component( 'GwtkDraggableResizable', GwtkDraggableResizable );
Vue.component( 'GwtkExpansionPanel', GwtkExpansionPanel );
Vue.component( 'GwtkIcon', GwtkIcon );
Vue.component( 'GwtkIconButton', GwtkIconButton );
Vue.component( 'GwtkListItem', GwtkListItem );
Vue.component( 'GwtkMenu', GwtkMenu );
Vue.component( 'GwtkNavButton', GwtkNavButton );
Vue.component( 'GwtkOverlay', GwtkOverlay );
Vue.component( 'GwtkPage', GwtkPage );
Vue.component( 'GwtkSelectable', GwtkSelectable );
Vue.component( 'GwtkSnackBar', GwtkSnackBar );
Vue.component( 'GwtkSwipePanel', GwtkSwipePanel );
Vue.component( 'GwtkTab', GwtkTab );
Vue.component( 'GwtkTabs', GwtkTabs );
Vue.component( 'GwtkTaskCard', GwtkTaskCard );
Vue.component( 'GwtkToolButton', GwtkToolButton );
Vue.component( 'GwtkTooltip', GwtkTooltip );

Vue.component( 'RgisPage', RgisPage );
Vue.component( 'GwtkDateTimePicker', GwtkDateTimePicker );
Vue.component( 'GwtkComponentHistory', GwtkComponentHistory);
Vue.component( 'GwtkDragAndDropArea', GwtkDragAndDropArea);
